export const sogData = [
    {
      id: 1,
      height: "20",
      // zone: "Flood Zone",
      textSize: "2xl",
      color: "#ff0000",
      title: "Start Up",
      stage: "Stage 1",
      employeeCount: "1 - 10",
    },
    {
      id: 2,
      height: "28",
      zone: "Flood Zone",
      textSize: "3xl",
      color: "#ff0000",
      title: "Ramp Up",
      stage: "Stage 2",
      employeeCount: "11 - 19",
    },
    {
      id: 3,
      height: "36",
      zone: "Wild Tunnel",
      textSize: "4xl",
      color: "#ff0000",
      title: "Delegation",
      stage: "Stage 3",
      employeeCount: "20 - 34",
    },
    {
      id: 4,
      height: "44",
      zone: "Flood Zone",
      textSize: "5xl",
      color: "#ff0000",
      title: "Professional",
      stage: "Stage 4",
      employeeCount: "35 - 57",
    },
    {
      id: 5,
      height: "52",
      zone: "Wild Tunnel",
      textSize: "6xl",
      color: "#ff0000",
      title: "Integration",
      stage: "Stage 5",
      employeeCount: "58 - 95",
    },
    {
      id: 6,
      height: "60",
      zone: "Flood Zone",
  
      textSize: "6xl",
      color: "#ff0000",
      title: "Strategic",
      stage: "Stage 6",
      employeeCount: "96 - 160",
    },
    {
      id: 7,
  
      height: "68",
      zone: "Wild Tunnel",
  
      textSize: "6xl",
      color: "#ff0000",
      title: "Visionary",
      stage: "Stage 7",
      employeeCount: "161 - 500",
    },
  ];
  